I think this may work, needs more testing

diff --git a/Alignment/HIPAlignmentAlgorithm/scripts/submitJobs_py b/Alignment/HIPAlignmentAlgorithm/scripts/submitJobs_py
--- a/Alignment/HIPAlignmentAlgorithm/scripts/submitJobs_py
+++ b/Alignment/HIPAlignmentAlgorithm/scripts/submitJobs_py
@@ -19,7 +19,6 @@ while (`bjobs -d -w |& grep $name/requeue$i` != "") # check if job name exists
 end
 
 @ MAX_JOB_ARRAY_SIZE = `bparams -a | grep MAX_JOB_ARRAY_SIZE | sed "s/.* = //"`
-@ MAX_JOB_ARRAY_SIZE = 5
 @ jobarrays = ( $jobs - 1 ) / $MAX_JOB_ARRAY_SIZE + 1
 
 echo Starting iteration = $i, final iteration = $iter, number of jobs = $jobs in $jobarrays arrays
@@ -47,14 +46,19 @@ while ($i <= $iter)
     foreach j (`seq 1 $jobarrays`)
         set id = `bjobs -J $name/align"$i"_$j | tail -n1 | awk '{print $1}'`
         echo "ID=$id"
-        if ( ! $?waitcondition ) then
-            set waitcondition = "done($id)"
+        if ( ! $?collectwaitcondition ) then
+            set collectwaitcondition = "done($id)"
+            set requeuewaitcondition = "numexit($id, > 0)"
+            set requeuejob = "brequeue -e $id"
         else
-            set waitcondition = "$waitcondition && done($id)"
+            set collectwaitcondition = "$collectwaitcondition && done($id)"
+            set requeuewaitcondition = "$requeuewaitcondition || numexit($id, > 0)"
+            set requeuejob = "$requeuejob || brequeue -e $id"    #this is a bit ugly, it will only requeue one array at a time
+                                                                 #it's needed to maintain the exit status of 0
         endif
     end
     echo "submit collect..."
-    bsub -q $queue -C 0 -J $name/collect$i -w "$waitcondition" \
+    bsub -q $queue -C 0 -J $name/collect$i -w "$collectwaitcondition" \
          -oo $odir/main/collect$i.out $odir/main/runScript.csh $workdir
 
 	 echo "submit stoprequeue"
@@ -69,8 +73,8 @@ while ($i <= $iter)
 
     while (`bjobs -d -J $name/requeue$i |& grep EXIT` == "")
     echo "Submitting requeue"
-      bsub -q cmsinter -C 0 -J $name/requeue$i -w "numexit($id, > 0)" \
-           -I brequeue -e $id
+      bsub -q cmsinter -C 0 -J $name/requeue$i -w "$requeuewaitcondition" \
+           -I "$requeuejob"
       sleep 60
     end
 
